spring:
    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

    zipkin:
        baseUrl: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
    instance:
        client:
            serverUrl:
                defauleZone: http://localhost:8761/eureka

logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
    
    level:
        org:
            springframework:
                web: DEBUG
