server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/departmentdb
        username: root
        password: Pass2018

    boot:
        message: "Hello, Department Spring cloud bus demo"

management:
    endpoints:
        web:
            exposure: 
                include: "*"

    tracing:
        sampling:
            probability: 1.0

eureka:
    instance:
        client:
            serverUrl:
                defauleZone: http://localhost:8761/eureka
