server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employeedb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: Pass2018

    boot:
        message: "Hello, Employee Spring cloud bus demo"

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

    zipkin:
        baseUrl: http://localhost:9411

# Actuator endpoint for circuit breaker
management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "health"
    endpoint:
        health:
            show-details: always

# Circuit Breaker configuraions
resilience4j:
    circuitbreaker:
        instances:
            employee-service:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED

# Retry configurations
retry:
    instances:
        employee-service:
          registerHealthIndicator: true
          maxAttempts: 3
          waitDuration: 1s
          #enableExponentialBackoff: true
          #exponentialBackoffMultiplier: 2

eureka:
    instance:
        client:
            serverUrl:
                defauleZone: http://localhost:8761/eureka
