server:
    port: 8084
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/organizationdb
        username: root
        password: Pass2018

    boot:
        message: "Hello, Department Spring cloud bus demo"

management:
    endpoints:
        web:
            exposure: 
                include: "*"

eureka:
    instance:
        client:
            serverUrl:
                defauleZone: http://localhost:8761/eureka
