server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/organizationdb
        username: root
        password: Pass2018


    jpa:
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update

    boot:
        message: "Hello, Department Spring cloud bus demo"

management:
    endpoints:
        web:
            exposure: 
                include: "*"

    tracing:
        sampling:
            probability: 1.0

eureka:
    instance:
        client:
            serverUrl:
                defauleZone: http://localhost:8761/eureka
